#!/bin/bash
# vim:ft=sh:
skip="-name \*.sw[opn] -o -name .gitmodules -o -name .git -o -name README.md -o -name dotdiff -o -name install"

if [ ${1:-nocp} = "cp" ]; then
  for file in `find . \( $skip \) -prune -o -type f -print`
  do
    orig=~/${file#*/}
    echo "diff -q $orig $file &>/dev/null || cp $orig $file"
  done

elif [ ${1:-nocp} = "find" ]; then
  find . \( $skip \) -prune -o -type f -print

else
  (for file in `find . \( $skip \) -prune -o -type f -print`
  do
    diff -ub $file ~/.vim/${file} 2>/dev/null
  done) | less -E -X
fi

