#!/bin/bash
find * \( -name .git\* -o -name vim.rb \) -prune -o -print| cpio -pdm ~/.vim
cp .vimrc ~
cp -i .Xdefaults .Xresources ~
set -x
if `type brew &>/dev/null`; then
  brew search the_silver_searcher && brew list the_silver_searcher || brew install the_silver_searcher
fi
